
public class LootSelector
{
    /*
     * 6 classes of items
     *  -weapons
     *  -armour
     *  -potions
     *  -scrolls
     *  -magical items
     *  -miscellaneous items
     */
    
    /*
     * 1. Hand Axe - R1 D2 H0 1Hnd (Attack Skill is Strength)
     * 2. Sword - R1 D2 H0 1Hnd (Attack Skill is Strength)
     * 3. Dagger - R1 D1 H1 1Hnd (Attack Skill is Strength. A Thief may use Dexterity for attack with this weapon instead)
     * 4. Pair of Daggers - R1 D1 H0 2Hnd Note: The hero may make 2 separate attacks per turn. If both attacks are successful, the dagger does an extra point of damage to one of the attacks (Attack Skill is Strength. A Thief may use Dexterity for attack with this weapon instead)
     * 5. Battle Axe – R1 D3 H0 2Hnd (Attack Skill is Strength)
     * 6. Iron Knuckles – R1 D1 H1 2Hnd Note: May make 2 separate attacks per turn. If both attacks are successful, the weapon does an extra point of damage to both attacks. (Attack Skill is Strength)
     * 7. Bow - R3 D2 H0 2Hnd (Attack Skill is Dexterity)
     * 8. Wand - R3 D1 H1 (Attack Skill is Wisdom)
     */
    
    /*
     * 1. Cloth - 1A
     * 2. Leather - 2A
     * 3. Platemail - 3A
     * 4. Buckler – 1A
     * 5. Heater Shield – 2A
     * 6. Tower Shield – 3A
     */
    
    /*
     * 1. Potion of Healing - Heals 4HP
     * 2. AP Restoration Potion - Fully restores your AP
     * 3. Potion of Explodify - Range 3 D4 attack to all enemies in target square, D2 attack to each enemy adjacent to target square.
     * 4. Potion of Invisibility - You may quaff this potion to pass through a room unnoticed by any monsters in it (except for the Boss monster). You can also open any chests in the room without having to kill the monsters.
     * 5. Potion of Fire Breathing - D2 attack to all monsters in a straight line (4 spaces) in front of your character.
     * 6. Unstable Potion - Add +1 to random stat. 1-2 Str, 3-4 Dex, 5-6 Wis
     */
    
    /*
     * 1. Scroll of + Str - +1 to your Str for 5 rounds
     * 2. Scroll of + Dex - +1 to your Dex for 5 rounds
     * 3. Scroll of + Wis - +1 to your Wis for 5 rounds
     * 4. Scroll of + HP - +2 to your HP for 5 rounds
     * 5. Scroll of Healing - Heals 8HP
     * 6. Scroll of Mapping - Reveals all rooms (including the treasures and monsters) connected to the current room.
     */
    
    /*
     * 1. Ring of Invisibility – 4 uses - You may pass through rooms undetected, You may not open chests or attack monsters while invisible from this ring
     * 2. Lucky Coin – 5 uses - Flip d6 at any time, on a 5-6 you may add or subtract 1 to another non-combat roll. This may only be used once per roll.
     * 3. Pocket Thief – 5 uses - You may automatically unlock one door or treasure chest per use.
     * 4. Mithril Armor - 4A
     * 5. Ring of Teleport - 3 uses – Move your character from the current room to one that has already been explored.
     * 6. Cartographers Glasses - 8 uses - Reveals a room adjacent to the current room without opening the door. 
     * 7. Bag of Items - 5 uses – Your character reaches into the bag and pulls out a item (generated by Treasure chart) with 5 bonus points to distribute. The item vanishes when you leave the room it was generated in.
     * 8. Spellbook - You may learn one new spell from the list of spells above.
     */
    
    /*
     * 1. Rope
     * 2. Fancy Clothes
     * 3. Torch
     * 4. Food
     */
    
    
    
    
    
    
    
    
}
